### ISSUE TITLE
Explanation of how to make RLE encoded bitmaps with Imagemagick

### ISSUE THREAD

**Issue by cromulus** [MHotchin/RLEBitmap#2]
I'd love to generate RLE encoded bitmaps server side for my esp32 project and decode them locally.

You mention imagemagick, is there a way to create the encoded file with imagemagick?

Thanks!

**Comment by MHotchin** [comment]
Imagemagick was used to create the bitmaps for the moon masks.  The encoding was done with Windows program 'bmper' that I wrote, the source of which lives under the 'extras' directory.
